---
services:
 devopsdb:
   image: sowmyareddy17/automation:db
   ports:
     - "3306:3306"
   deploy:
     replicas: 2
   networks:
     - mynetwork
 application:
   image: appimage
   ports:
     - "1111:8080"
   deploy:
     replicas: 2
   networks:
     - mynetwork
   depends_on:
     - "devopsdb"
networks:
  mynetwork:
    driver: overlay
